[package]
name = "fdg-img"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.2"
fdg-sim = { path = "../fdg-sim/" }

[dev-dependencies]
fdg-sim = { path = "../fdg-sim/",  features = ["json"] }